###################### POSTS ######################
# GET http://192.168.86.33:9002/posts/API?sellerID=Asem2&postCategories=car&location=amman&name=mercedes&q=salt
# GET http://192.168.86.33:9002/posts/API/getOffers?sellerID=hello&buyerOffers=buyer889111
# POST http://192.168.86.33:9002/posts/API/postAdvertisement
# {		"sellerID": "Asem",
#         "postCategories": "i am new data",
#         "location":"Amman",
#         "name": "mercedes",
#         "additionalInfo": "c200",
#     	"imgUrl": "https://images.summitmedia-digital.com/topgear/images/2018/07/31/BMW-520d1.jpg"}

# PATCH http://192.168.86.33:9002/posts/API/postOffers?id=5dcff00c05c23f2186fa8e58&buyer889111=85k
# DELETE http://192.168.86.33:9002/posts/API/5dd00484a085e235612f478d

###################### USERS ######################

# GET http://192.168.86.33:9002/users/API/data
# GET http://192.168.86.33:9002/users/API/auth?email=asem@qaffaf.com&password=a12345
# POST http://192.168.86.33:9002/users/API/new
# {
#  "name":"ASEM22", 
#     "email": "ADAM2@gmail.com",
#     "password": "123456"
# }
# DELETE http://192.168.86.33:9002/users/API/delete/5dd01115afc48440677b7285